#!name=微博&微博国际版净化
#!system=ios
#!originURL=https://github.com/RayJiang16/shadowrocket_diy_rules
#!forkURL=https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/Weibo.conf

[Url Rewrite]

# Fork
# 微博国际版_趋势页热门影片@ddgksf2013
^https?:\/\/api\.weibo\.cn\/\d\/cardlist\?v_f=.*Weibo_intl - reject
# 微博_用户推荐弹窗@ddgksf2013
^https?:\/\/api\.weibo\.cn\/\d\/profile\/recommend_popuser - reject

[Script]
# 微博_开屏广告预加载处理
weiboad=type=http-response,pattern=^https?:\/\/boot*.*weibo\.c(n|om)\/v\d\/ad,requires-body=1,script-path=https://raw.githubusercontent.com/RayJiang16/shadowrocket_diy_rules/main/js/weibo.js
weiboad=type=http-response,pattern=^https?:\/\/api\.*weibo\.c(n|om)\/\d\/ad,requires-body=1,script-path=https://raw.githubusercontent.com/RayJiang16/shadowrocket_diy_rules/main/js/weibo.js
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/ad,requires-body=1,script-path=https://raw.githubusercontent.com/RayJiang16/shadowrocket_diy_rules/main/js/weibo.js
weiboad=type=http-response,pattern=^https?:\/\/boot.*weibo\.com\/v\d\/ad\/realtime,requires-body=1,script-path=https://raw.githubusercontent.com/RayJiang16/shadowrocket_diy_rules/main/js/weibo.js
# 微博_信息流广告
weiboad=type=http-response,pattern=^https?:\/\/weibointl\.api\.*weibo\.c(n|om)\/portal\.php(.*c=ad.*|.*a=get_coopen_ads.*),requires-body=1,script-path=https://raw.githubusercontent.com/RayJiang16/shadowrocket_diy_rules/main/js/weibo.js

# Fork
# > 微博_首页顶部homeExtend@ddgksf2013
weiboad=type=http-response,pattern=^https?:\/\/api\.weibo\.cn\/\d\/groups\/allgroups\/v\d,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
# > 微博国际版_帖子下方广告banner@ddgksf2013
weiboad=type=http-response,pattern=^https?:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?a=open_app,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
# > 微博_开屏广告预加载处理@ddgksf2013
weiboad=type=http-response,pattern=^https?:\/\/boot.*weibo\.com\/v\d\/ad\/preload,requires-body=1,script-path=https://raw.githubusercontent.com/RayJiang16/shadowrocket_diy_rules/main/js/weibo.js

[MITM]
hostname = %APPEND% api.weibo.cn, api.weibo.com, *.api.weibo.cn, *.api.weibo.com, mapi.weibo.com, mapi.weibo.cn, *.uve.weibo.com, new.vip.weibo.cn, boot.biz.weibo.com