#!name=微博&微博国际版净化
#!system=ios
#!originURL=https://github.com/RayJiang16/shadowrocket_diy_rules
#!forkURL=https://raw.githubusercontent.com/ddgksf2013/Rewrite/master/AdBlock/Weibo.conf

[Url Rewrite]

^https?:\/\/bootpreload\.uve\.weibo\.com\/v\d\/ad\/ - reject
^https?:\/\/bootpreload\.uve\.weibo\.com\/v\d\/ad\/preload - reject
^https?:\/\/boot*.*weibo\.c(n|om)\/v\d\/ad - reject
^https?:\/\/api\.*weibo\.c(n|om)\/\d\/ad - reject
^https?:\/\/open\.e\.kuaishou\.com\/ - reject
^https?:\/\/mi\.gdt\.qq\.com\/ - reject
^https?:\/\/v2mi\.gdt\.qq\.com\/ - reject
^https?:\/\/adstrategy\.biz\.weibo\.com\/ - reject
^https?:\/\/canvas-cdn\.gdt\.qq\.com\/ - reject
^https?:\/\/api\.gdt\.touch-moblie\.com\/ - reject
^https?:\/\/api\.touch-moblie\.com\/ - reject
^https?:\/\/*\.adkwai\.com\/ - reject
^https?:\/\/p66-ad\.adkwai\.com\/ - reject

[Script]
# 微博快手_开屏广告
weiboad=type=http-response,pattern=^https?:\/\/open\.e\.kuaishou\.com\/.*,requires-body=1,script-path=https://raw.githubusercontent.com/RayJiang16/shadowrocket_diy_rules/main/js/weibo.js
weiboad=type=http-response,pattern=^https?:\/\/mi\.gdt\.qq\.com\/.*,requires-body=1,script-path=https://raw.githubusercontent.com/RayJiang16/shadowrocket_diy_rules/main/js/weibo.js

# 微博_开屏广告预加载处理
weiboad=type=http-response,pattern=^https?:\/\/boot*.*weibo\.c(n|om)\/v\d\/ad\/,requires-body=1,script-path=https://raw.githubusercontent.com/RayJiang16/shadowrocket_diy_rules/main/js/weibo.js
weiboad=type=http-response,pattern=^https?:\/\/api\.*weibo\.c(n|om)\/\d\/ad,requires-body=1,script-path=https://raw.githubusercontent.com/RayJiang16/shadowrocket_diy_rules/main/js/weibo.js
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/ad,requires-body=1,script-path=https://raw.githubusercontent.com/RayJiang16/shadowrocket_diy_rules/main/js/weibo.js
# 微博_信息流广告
weiboad=type=http-response,pattern=^https?:\/\/weibointl\.api\.*weibo\.c(n|om)\/portal\.php(.*c=ad.*|.*a=get_coopen_ads.*),requires-body=1,script-path=https://raw.githubusercontent.com/RayJiang16/shadowrocket_diy_rules/main/js/weibo.js

# Fork
# > 微博_首页顶部homeExtend@ddgksf2013
weiboad=type=http-response,pattern=^https?:\/\/api\.weibo\.cn\/\d\/groups\/allgroups\/v\d,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
# > 微博国际版_帖子下方广告banner@ddgksf2013
weiboad=type=http-response,pattern=^https?:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?a=open_app,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
# > 微博_去广告以及去除各部分推广模块@zmqcherish,@ddgksf2013
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/(searchall|page\?|messageflow),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/statuses/(unread_)?friends(/|_)timeline,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/groups/timeline,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/statuses/(container_timeline|unread_hot_timeline|extend|video_mixtimeline|unread_topic_timeline),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/profile/(me|container_timeline),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/video/(community_tab|remind_info|tiny_stream_video_list),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/search/(finder|container_timeline|container_discover),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/(checkin/show|\!/live/media_homelist|comments/build_comments|container/get_item),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
weiboad=type=http-response,pattern=^https?:\/\/m?api\.weibo\.c(n|om)\/\d\/cardlist,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js

# > 微博国际版_屏蔽sdkad@ddgksf2013
weiboad=type=http-response,pattern=^https?://(sdk|wb)app\.uve\.weibo\.com(/interface/sdk/sdkad.php|/wbapplua/wbpullad.lua),requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
# > 微博国际版_趋势顶部Card去广告@ddgksf2013
weiboad=type=http-response,pattern=^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php.*feed&a=trends,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
# > 微博国际版_屏蔽用户VIP栏@ddgksf2013
weiboad=type=http-response,pattern=^https?:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?a=user_center,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js
# > 微博国际版_热搜处理@ddgksf2013
weiboad=type=http-response,pattern=^https?:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?a=search_topic,requires-body=1,script-path=https://github.com/ddgksf2013/Scripts/raw/master/weibo_json.js

# 尝试去新开屏
weiboad=type=http-response,pattern=^https?:\/\/adstrategy\.biz\.weibo\.com\/.*,requires-body=1,script-path=https://raw.githubusercontent.com/RayJiang16/shadowrocket_diy_rules/main/js/weibo.js

[MITM]
hostname = %APPEND% api.weibo.cn, api.weibo.com, *.api.weibo.cn, *.api.weibo.com, mapi.weibo.com, mapi.weibo.cn, *.uve.weibo.com, new.vip.weibo.cn, boot.biz.weibo.com, bootpreload.uve.weibo.com, open.e.kuaishou.com, *.gdt.qq.com, *.biz.weibo.com, api.gdt.touch-moblie.com, *.adkwai.com, adstrategy.biz.weibo.com, api.touch-moblie.com, canvas-cdn.gdt.qq.com