#!name=知乎净化
#!system=ios
#!originURL=https://github.com/RayJiang16/shadowrocket_diy_rules
#!forkURL=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/zheye/zheye.snippet

[Url Rewrite]
^https?:\/\/118\.89\.204\.198 - reject
^https?:\/\/103\.41\.167\.237 - reject
^https?:\/\/2402:4e00:1200:ed00:0:9089:6dac:96b6 - reject
# 屏蔽下发的配置，如皮肤等
^https?:\/\/api\.zhihu\.com\/ab\/api\/v1\/products\/zhihu\/platforms\/ios\/config - reject
# 拦截开屏广告
^https?:\/\/api\.zhihu\.com\/commercial_api\/launch_v2\? - reject
^https?:\/\/api\.zhihu\.com\/commercial_api\/real_time_launch_v2\? - reject
# 拦截品牌提问广告
^https?:\/\/api\.zhihu\.com\/brand\/question\/\d+/card\? - reject
^https?:\/\/www\.zhihu\.com\/api\/v\d+\/brand\/question/\d+/card\? - reject
# 去除底部标签页关注人角标
^https?:\/\/api\.zhihu\.com\/moments\/tab_v2 - reject
# 去除消息通知角标
^https?:\/\/api\.zhihu\.com\/(notifications\/v\d\/count) - reject
# 拦截回答下的卡片广告
^https?:\/\/www\.zhihu\.com\/api\/v\d\/answers\/\d+\/recommendations - reject
# 拦截应用内弹窗
^https?:\/\/api\.zhihu\.com\/me\/guides - reject
# 去除关注页最常访问
^https?:\/\/api\.zhihu\.com\/moments\/recent - reject
# 拦截推荐页顶部广告
^https?:\/\/api\.zhihu\.com\/api\/v4\/ecom_data\/config - reject
# 底栏加号的广告
^https?:\/\/api\.zhihu\.com\/content-distribution-core\/bubble\/common\/settings - reject
# 推荐页搜索栏左侧图标
^https?:\/\/api\.zhihu\.com\/feed\/render\/revisit\/current_reading - reject
# 疑似推荐页内容更新红点
^https?:\/\/api\.zhihu\.com\/feed\/render\/revisit\/tag_config - reject
# 去除回答页的相关搜索
^https?:\/\/www\.zhihu\.com\/api\/v\d+\/search\/related_queries\/answer - reject
# 暂不清楚作用
^https?:\/\/api\.zhihu\.com\/commercial_api\/banners_v3\/app_topstory_banner - reject
^https?:\/\/api\.zhihu\.com\/ad-style-service\/request - reject

[Script]
# 获取用户信息 - 隔离用户数据，开启本地会员等
zhihu=type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/people\/,requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
# 优化软件配置 - 优化下发的配置文件来实现某些效果
zhihu=type=http-response,pattern=^https?:\/\/m-cloud\.zhihu\.com\/api\/cloud\/config\/all\?,requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
# 用户信息 - 修改用户盐值
zhihu=type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/user-credit\/basis,requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
# 关注页 - 内容优化及屏蔽转发的黑名单用户想法
zhihu=type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/moments_v3\?,requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
# 推荐页 - 移除黑名单用户发布的文章、去除广告，及自定义一些屏蔽项目
zhihu=type=http-response,pattern=^https:\/\/api\.zhihu\.com\/topstory\/recommend,requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
# 黑名单页 - 同步黑名单数据
zhihu=type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/settings\/blocked_users,requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
# 问题的回答列表 - 移除黑名单用户的回答、去除广告
zhihu=type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/(v4\/)?questions\/\d+,requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
# 回答信息流 - 移除黑名单用户的回答、去除广告
zhihu=type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/next-(data|bff|render),requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
# 回答页底部评论摘要 - 移除黑名单用户发表的评论
zhihu=type=http-response,pattern=^https?:\/\/www\.zhihu\.com\/api\/v4\/comment_v5\/answers\/\d+\/abstract_comment\?,requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
# 评论页及子页面 - 去除黑名单用户发表的评论
zhihu=type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/(comment_v5\/)?(answers|comments?|articles|pins)\/\d+\/(root_|child_)?comments?,requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
# 消息页 - 折叠官方消息、屏蔽营销消息
zhihu=type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/notifications\/v3\/(message|timeline\/entry\/system_message),requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
# 回答页 - 内容优化，付费、营销、推广内容文首提醒
zhihu=type=http-response,pattern=^https?:\/\/www\.zhihu\.com\/appview\/v2\/answer\/.*(entry=(?!(preload-topstory|preload-search|preload-subscription)))?,requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
# 回答页 - 屏蔽下翻出现的黑名单用户的回答
zhihu=type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/next\?,requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
# 文章页 - 去除底部广告
zhihu=type=http-response,pattern=^https?:\/\/www\.zhihu\.com\/api\/v\d\/articles\/\d+\/recommendation\?,requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
# 热榜页 - 去除广告
zhihu=type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/topstory\/hot-lists?(\?|\/),requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
# 搜索页 - 去除预置广告
zhihu=type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/search\/preset_words\?,requires-body=1,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js

[MITM]
hostname = %APPEND%  118.89.204.198,103.41.167.237,2402:4e00:1200:ed00:0:9089:6dac:96b6,www.zhihu.com,api.zhihu.com,zhuanlan.zhihu.com,appcloud2.zhihu.com,m-cloud.zhihu.com,103.41.167.236,103.41.167.234,103.41.167.235,103.41.167.226